### ISSUE TITLE
Uncaught (in promise) Error: No address for Uniswap Multicall Contract on chain id: 11155111

### ISSUE THREAD

**Issue by khang-uit** [Uniswap/examples#73]
I got this error when try to use sepolia network in v3sdk/routing
```
multicall-uniswap-provider.ts:45 Uncaught (in promise) Error: No address for Uniswap Multicall Contract on chain id: 11155111
    at new UniswapMulticallProvider (multicall-uniswap-provider.ts:45:1)
    at new AlphaRouter (alpha-router.ts:385:1)
    at generateRoute (routing.ts:27:1)
    at Example.tsx:62:1
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
```
this is in config.ts file
```
export const CurrentConfig: ExampleConfig = {
  env: Environment.WALLET_EXTENSION,
  rpc: {
    local: 'http://localhost:8545',
    mainnet: 'https://sepolia.infura.io/v3/token',
  },
```

create new router script
```
  const router = new AlphaRouter({
    chainId: 11155111,
    provider: getMainnetProvider(),
  })
```

**Comment by Ladmv** [comment]
Have you solved this problem?

**Comment by dcapitator** [comment]
they do not support sepolia chain i guess

**Comment by hustlebuilder** [comment]
I'm having the same problem. Which SDK version allows them to support Base and other chains?
