### ISSUE TITLE
Example does not work!

### ISSUE THREAD

**Issue by elshapovalov** [Uniswap/examples#78]
I try to run [Uniswap example](https://github.com/Uniswap/examples/tree/main/v3-sdk/swap-and-add-liquidity) and always get error in browser console:
**Uncaught ReferenceError: Browser is not defined
at Va (encode.js:49:1)**

Can anybody help me?

**Comment by cypruspound** [comment]
I have the same issue ! 

Initially i have installed @uniswap/widget to check it out but later on i changed my mind i decided not to work with it so i removed it ... i changed webpack 5 to 4 version and then again went back to 5 because i had several issues which i have resolved
however i still have the same error ...
I saw that another package that I am using [smart-order-router] also depends on  "brotli": "^1.3.3",  
unfortunately i cannot remove smart-order-router .

the error in brotli is in this line : exports.compress = require('./compress');

**Comment by robertxd30** [comment]
I have same issue

**Comment by upendradhamaladev** [comment]
I have got the same issue too. Stuck on this since a week. I tried different solutions but none of them worked. 

![image](https://github.com/Uniswap/examples/assets/87364448/d5b84581-7e44-4b97-a41e-7df7bf93e076)

**Comment by janndriessen** [comment]
> I try to run [Uniswap example](https://github.com/Uniswap/examples/tree/main/v3-sdk/swap-and-add-liquidity) and always get error in browser console: **Uncaught ReferenceError: Browser is not defined at Va (encode.js:49:1)**
> 
> Can anybody help me?

Probably related to this: https://github.com/Uniswap/smart-order-router/issues/484
